// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80kAm2DUGrcT6G1nUvaPTrbRiI5xmlwA',
    appId: '1:799552571780:web:a79dd1d43644f5278d75d1',
    messagingSenderId: '799552571780',
    projectId: 'dndapp-f609a',
    authDomain: 'dndapp-f609a.firebaseapp.com',
    databaseURL: 'https://dndapp-f609a-default-rtdb.firebaseio.com',
    storageBucket: 'dndapp-f609a.appspot.com',
    measurementId: 'G-8Z5K6CEY9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3HtdivWtTZSlXZanLOm9CS9a2War314',
    appId: '1:799552571780:android:4f18c3855ea44e538d75d1',
    messagingSenderId: '799552571780',
    projectId: 'dndapp-f609a',
    databaseURL: 'https://dndapp-f609a-default-rtdb.firebaseio.com',
    storageBucket: 'dndapp-f609a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5J6ahB7StYz8VxK16XTJacSUyrvQUIxw',
    appId: '1:799552571780:ios:ea4e973e24568ca98d75d1',
    messagingSenderId: '799552571780',
    projectId: 'dndapp-f609a',
    databaseURL: 'https://dndapp-f609a-default-rtdb.firebaseio.com',
    storageBucket: 'dndapp-f609a.appspot.com',
    iosClientId: '799552571780-ga5jl92hsh8hjbgo4380u9duqgigl3an.apps.googleusercontent.com',
    iosBundleId: 'com.example.dndcompanionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5J6ahB7StYz8VxK16XTJacSUyrvQUIxw',
    appId: '1:799552571780:ios:ea4e973e24568ca98d75d1',
    messagingSenderId: '799552571780',
    projectId: 'dndapp-f609a',
    databaseURL: 'https://dndapp-f609a-default-rtdb.firebaseio.com',
    storageBucket: 'dndapp-f609a.appspot.com',
    iosClientId: '799552571780-ga5jl92hsh8hjbgo4380u9duqgigl3an.apps.googleusercontent.com',
    iosBundleId: 'com.example.dndcompanionapp',
  );
}
